# Generated by Django 5.0.7 on 2025-03-13 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя клиента')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта клиента')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема сообщения')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Рассылка № ', max_length=30, verbose_name='название рассылки')),
                ('datetime_first_mailing', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время начала рассылки')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания рассылки')),
                ('frequency', models.CharField(choices=[('once', 'Однократно'), ('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц'), ('yearly', 'Раз в год')], default='once', max_length=150, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('activated', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=150, verbose_name='Статус рассылки')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка')),
                ('client', models.ManyToManyField(to='mailing.client', verbose_name='Клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_last_mailing', models.DateTimeField(verbose_name='Дата и время последней отправки рассылки')),
                ('status_attempt', models.BooleanField(default=False, verbose_name='Статус')),
                ('server_answer', models.CharField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='текст рассылки')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
    ]
