# Generated by Django 5.0.7 on 2025-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Рассылка № ', max_length=30, verbose_name='название рассылки'),
        ),
    ]
